name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: boost
      run: sudo apt-get install libboost-all-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make
